#!/usr/bin/env bash
set -e

# Start SSH daemon in background
sudo service ssh start

# Check required environment variables
if [[ -z "$GIT_REPO" ]]; then
    echo "ERROR: GIT_REPO environment variable is required"
    exit 1
fi

if [[ -z "$GITHUB_TOKEN" ]]; then
    echo "ERROR: GITHUB_TOKEN environment variable is required"
    exit 1
fi

if [[ -z "$PROMPT" ]]; then
    echo "ERROR: PROMPT environment variable is required"
    exit 1
fi

if [[ -z "$TASK_ID" ]]; then
    echo "ERROR: TASK_ID environment variable is required"
    exit 1
fi

# Authenticate with GitHub CLI
echo "$GITHUB_TOKEN" | gh auth login --with-token

# Clone the repository
echo "→ Cloning repository: $GIT_REPO"
git clone --depth 1 "$GIT_REPO" repo
cd repo

echo "→ Repository cloned successfully"
echo "→ Running Claude Code CLI with prompt: $PROMPT"

# Run Claude Code CLI with the user-supplied prompt
claude --code --prompt "$PROMPT" || {
    echo "✗ Claude Code execution failed"
    exit 1
}

echo "→ Claude Code execution completed"

# Create a branch, commit, and push
BRANCH_NAME="swarm/ai/$TASK_ID"
echo "→ Creating branch: $BRANCH_NAME"

git checkout -b "$BRANCH_NAME"
git add -A

# Check if there are any changes to commit
if git diff --cached --quiet; then
    echo "ℹ No changes to commit"
    exit 0
fi

git commit -m "feat(ai): task $TASK_ID produced by Claude

This commit contains changes generated by Claude AI assistant
in response to the following prompt:

$PROMPT

🤖 Generated with Claude Code
Task ID: $TASK_ID"

echo "→ Pushing branch to origin"
git push origin "$BRANCH_NAME"

echo "→ Creating pull request"
gh pr create \
    --title "AI Task $TASK_ID: $(echo "$PROMPT" | head -c 50)..." \
    --body "$(cat <<EOF
## Summary
This pull request was automatically generated by Claude AI in response to task $TASK_ID.

**Prompt:** $PROMPT

## Changes
- AI-generated code changes based on the provided prompt
- All changes have been automatically committed and pushed

## Review Notes
- Please review all changes carefully before merging
- Test the changes in your development environment
- Consider the security implications of any new dependencies or configurations

🤖 Generated with [Claude Code](https://claude.ai/code)

**Task ID:** $TASK_ID
EOF
)" \
    --head "$BRANCH_NAME"

echo "✓ Pull request created successfully"
echo "→ Task $TASK_ID completed"

# Exit successfully - this will trigger Daytona to shut down the workspace
exit 0