// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RepositoryTS = { id: number, github_repo_id: bigint, owner: string, name: string, full_name: string, user_id: number, is_private: boolean | null, created_at: string | null, last_fetched_at: string | null, github_pushed_at?: string, };
