// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentTodo } from "./AgentTodo";
import type { Run } from "./Run";
import type { TaskLogsPaginated } from "./TaskLogsPaginated";

export type RunWithMeta = { run: Run, todos: Array<AgentTodo>, logs: TaskLogsPaginated, };
