// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageWithRun } from "./MessageWithRun";
import type { Task } from "./Task";

export type TaskDetails = { task: Task, messages: Array<MessageWithRun>, };
