// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Task = { id: number, user_id: number, repository_id: number, title: string, description: string | null, status: string | null, github_pr_url: string | null, daytona_workspace_id: string | null, workspace_hostname: string | null, daytona_session_id: string | null, daytona_command_id: string | null, created_at: string | null, updated_at: string | null, };
